function [image_b] = task2_border(image, bordersize)
%TASK2_BORDER create a border around an image with bordersize pixels
%   the border is generated by replication of the border pixels

    size_y = size(image, 1);
    size_x = size(image, 2);
    
    size_y_b = size_y + 2 * bordersize;
    size_x_b = size_x + 2 * bordersize;
    
    min_y = 1 + bordersize;
    max_y = size_y_b - bordersize;
    min_x = 1 + bordersize;
    max_x = size_x_b - bordersize;
    
    
    % add replicated border to image
    image_b = zeros(size_y_b, size_x_b);
    
    % center image
    image_b(min_y:max_y, min_x:max_x) = image(:,:);
    
    % replicate left, right, top, bottom borders
    image_b(min_y:max_y, 1:bordersize) = repmat(image(:,1), 1, bordersize);
    image_b(min_y:max_y, max_x+1:size_x_b) = repmat(image(:,size_x), 1, bordersize);
    image_b(1:bordersize, min_x:max_x) = repmat(image(1,:), bordersize, 1);
    image_b(max_y+1:size_y_b, min_x:max_x) = repmat(image(size_y,:), bordersize, 1);
    
    % replicate upper left, upper right, lower left, lower right corners
    image_b(1:bordersize, 1:bordersize) = repmat(image(1,1), bordersize, bordersize);
    image_b(1:bordersize, max_x+1:size_x_b) = repmat(image(1,size_x), bordersize, bordersize);
    image_b(max_y+1:size_y_b, 1:bordersize) = repmat(image(size_y,1), bordersize, bordersize);
    image_b(max_y+1:size_y_b, max_x+1:size_x_b) = repmat(image(size_y,size_x), bordersize, bordersize);

end

